### ISSUE TITLE
" System.AggregateException" during readin BTC Transactions

### ISSUE THREAD

**Issue by n4kashu** [bizanc/Bizanc.io.Core#1]
**To Reproduce**
1. Go to 'start sudo docker-compose -f docker-compose.yml up --build'
2. in log:
Building masternode
Step 1/10 : FROM microsoft/dotnet:2.1-sdk AS build-env
 ---> 6e1c48456450
Step 2/10 : WORKDIR /app
 ---> Using cache
 ---> eab59b43e9e7
Step 3/10 : COPY ./. ./
 ---> Using cache
 ---> 7a436e242ed3
Step 4/10 : RUN dotnet restore Bizanc.io.Matching.sln
 ---> Using cache
 ---> 4e8205f7373a
Step 5/10 : RUN mkdir out
 ---> Using cache
 ---> e9d0128fe316
Step 6/10 : RUN dotnet publish Bizanc.io.Matching.App/Bizanc.io.Matching.App.csproj -c Release -o ./out
 ---> Using cache
 ---> b8641a820359
Step 7/10 : FROM microsoft/dotnet:2.1.5-aspnetcore-runtime
 ---> 1fe6774e5e9e
Step 8/10 : WORKDIR /app
 ---> Using cache
 ---> fd52d7de7bda
Step 9/10 : COPY --from=build-env app/Bizanc.io.Matching.App/out ./
 ---> Using cache
 ---> 0f6657e726de
Step 10/10 : ENTRYPOINT ["dotnet", "Bizanc.io.Matching.App.dll"]
 ---> Using cache
 ---> df29827591d4
Successfully built df29827591d4
Successfully tagged bizancio.core:latest
Starting bizanciocore_masternode_1 ... 
Starting bizanciocore_masternode_1 ... done
Attaching to bizanciocore_masternode_1
masternode_1  | Wallet Recoved
masternode_1  | Private 9uXM8YuhGwNQTi4kabpr5xTZDB7iQqpmvh4qb36yiXpn
masternode_1  | Public 2DQg1m8JXXjoQNxmtFTnYBuudpcyQRYB4BmFHvk1UJg2
masternode_1  | Initiling Empty Chain
masternode_1  | Listener started...
masternode_1  | 226 ETH deposits loaded
masternode_1  | Reading BTC Deposits.....

masternode_1  | System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
masternode_1  |    --- End of inner exception stack trace ---
masternode_1  |    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
masternode_1  |    at Bizanc.io.Matching.Infra.Connector.BitcoinConnector.<GetBtcDeposit>b__2_0() in /app/Bizanc.io.Matching.Infra/Connector/BitcoinConnector.cs:line 27
masternode_1  |    at System.Threading.Tasks.Task`1.InnerInvoke()
masternode_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
masternode_1  | --- End of stack trace from previous location where exception was thrown ---
masternode_1  |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
masternode_1  | --- End of stack trace from previous location where exception was thrown ---
masternode_1  |    at Bizanc.io.Matching.Infra.Connector.BitcoinConnector.GetBtcDeposit() in /app/Bizanc.io.Matching.Infra/Connector/BitcoinConnector.cs:line 25
masternode_1  |    at Bizanc.io.Matching.Infra.Connector.CryptoConnector.LoadBTC() in /app/Bizanc.io.Matching.Infra/Connector/CryptoConnector.cs:line 70
masternode_1  | ---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
masternode_1  | 
masternode_1  | Reading BTC Deposits.....

3. node hangs on this repeating and failing

**Comment by n4kashu** [comment]
the same behavior on various machines. linux, win... since the reset. yesterday everything started nicely. wallet got generated, synced and started mining..

**Comment by shade** [comment]
I have the same issue...

**Comment by bizanc** [comment]
The btc deposits are loaded using QBitNinja public API:  http://tapi.qbit.ninja/
Since we still don't have money to deploy a node to support our network, we need to use this public API that has some outages. Really sorry that happend in the moment that you tested it.

**Comment by bizanc** [comment]
I have disable BTC deposits load till we deploy a QBitNinja node or it get backs to work. Please feel free test.  I'll close this issue but let me know if something wrong happen.
